# Generated by Django 4.0.5 on 2022-06-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(blank=True, default='prodImage/default_prod_image.png', upload_to='prodImage'),
        ),
    ]
